packages:
  - '.'
overrides:
  deepmerge-ts: '>=8.0.0'
  mysql2: '>=3.22.0'
  esbuild: '>=0.28.1'
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  '@parcel/watcher': true
  '@swc/core': true
