-- Rollout: 004_create_messages_notifications
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 004_create_messages_notifications.sql

\i scripts/004_create_messages_notifications.sql
