-- Rollout: 005_create_audit_and_feature_flags
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 005_create_audit_and_feature_flags.sql

\i scripts/005_create_audit_and_feature_flags.sql
