-- Rollout: 009_supabase_security_hardening
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 009_supabase_security_hardening.sql

\i scripts/009_supabase_security_hardening.sql
